//! POSIX and GNU argument scanning

use crate::error::Error;
use crate::meta::{CommandDef, Owned, Static, Storage};
use crate::polarity::Polarity;
use crate::policy::{ExclusiveRule, NumericOperandRule, ValueRule};
use crate::style::Style;

mod classify;
mod config;
mod cursor;
mod long;
mod numeric;
mod reject;
mod short;
mod value;

use classify::{ArgClass, classify, is_polar};
use config::{ScanConfig, is_long, parsed_char};
use cursor::Cursor;
use long::process_long;
use numeric::{process_first_numeric, process_numeric_operand};
use short::process_cluster;

/// How to handle unrecognized flag characters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[expect(clippy::exhaustive_enums, reason = "two-state behavioral switch")]
pub enum OnUnknown {
    /// Return an error (standard POSIX behavior).
    #[default]
    Reject,
    /// Treat the entire arg as an operand (echo-style).
    PassThrough,
}

/// Classification of a declared flag for the parser.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum FlagKind {
    /// Boolean toggle — presence means true.
    Bool,
    /// Takes a value (next arg or inline remainder).
    Value,
    /// Polarity-aware — tracks `-x` vs `+x`.
    Polar,
    /// Polarity-aware and takes a value.
    PolarValue,
    /// Accepted but ignored (no-op).
    Noop,
}

/// A declared flag that the parser recognizes.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    clippy::struct_excessive_bools,
    reason = "static config generated by derive"
)]
pub struct FlagDef<S: Storage = Static> {
    /// Identity char: the short flag (`-v`), or a private-use codepoint for long-only flags.
    pub ch: char,
    /// The GNU long name without dashes (e.g., "verbose"); empty if short-only.
    pub long: S::Text,
    /// Extra long names resolving to this flag (e.g. "silent" aliasing "quiet").
    pub aliases: S::List<S::Text>,
    /// What kind of flag this is.
    pub kind: FlagKind,
    /// Flags cleared when this one fires (last-wins mutex).
    pub clears: S::List<char>,
    /// Human-readable description (from doc comment).
    pub desc: S::Text,
    /// Value placeholder (empty for bool flags, e.g. "PATH" for valued).
    pub value_name: S::Text,
    /// When true, omit from generated help (still parseable).
    pub hidden: bool,
    /// Whether ecmd may execute this flag internally.
    pub implemented: bool,
    /// Whether this flag accepts more than one occurrence.
    pub repeatable: bool,
    /// Whether a separated value may begin with a hyphen.
    pub allow_hyphen_values: bool,
    /// The accepted values, when the flag admits only a fixed set.
    pub possible_values: S::List<S::Text>,
    /// The values help lists, when they differ from the accepted set.
    pub help_values: S::List<S::Text>,
    /// The value used when the flag is absent; none when empty.
    pub default_value: S::Text,
    /// Replaces the generated label in help; generated when empty.
    pub help_label: S::Text,
    /// Aliases help lists; parsing accepts these as well as `aliases`.
    pub visible_aliases: S::List<S::Text>,
}

impl FlagDef<Static> {
    /// A zero-valued base so a literal survives new fields being added
    pub const EMPTY: Self = Self {
        ch: '\0',
        long: "",
        aliases: &[],
        kind: FlagKind::Bool,
        clears: &[],
        desc: "",
        value_name: "",
        hidden: false,
        implemented: false,
        repeatable: false,
        allow_hyphen_values: false,
        possible_values: &[],
        help_values: &[],
        default_value: "",
        help_label: "",
        visible_aliases: &[],
    };
}

impl FlagDef<Static> {
    /// Copy every borrowed field into owned storage
    #[must_use]
    pub fn into_owned(self) -> FlagDef<Owned> {
        FlagDef {
            ch: self.ch,
            long: self.long.to_owned(),
            aliases: self
                .aliases
                .iter()
                .map(|alias| (*alias).to_owned())
                .collect(),
            kind: self.kind,
            clears: self.clears.to_vec(),
            desc: self.desc.to_owned(),
            value_name: self.value_name.to_owned(),
            hidden: self.hidden,
            implemented: self.implemented,
            repeatable: self.repeatable,
            allow_hyphen_values: self.allow_hyphen_values,
            possible_values: self
                .possible_values
                .iter()
                .map(|value| (*value).to_owned())
                .collect(),
            help_values: self
                .help_values
                .iter()
                .map(|value| (*value).to_owned())
                .collect(),
            default_value: self.default_value.to_owned(),
            help_label: self.help_label.to_owned(),
            visible_aliases: self
                .visible_aliases
                .iter()
                .map(|value| (*value).to_owned())
                .collect(),
        }
    }
}

/// Result of parsing a single flag occurrence.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum Parsed {
    /// A boolean flag was set.
    Bool(char),
    /// A valued flag with its argument.
    Value(char, String),
    /// A polarity flag was set.
    Polar(char, Polarity),
    /// A polarity flag with a value.
    PolarValue(char, Polarity, String),
}

/// Output of a successful `scan` call.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(clippy::exhaustive_structs, reason = "result of scan")]
pub struct ScanResult {
    /// Parsed flag occurrences in order.
    pub flags: Vec<Parsed>,
    /// Remaining positional operands.
    pub operands: Vec<String>,
    /// Declared flags that require an external implementation.
    pub unimplemented: Vec<String>,
}

/// Scan arguments against declared flags
pub fn scan<S: Storage>(
    args: &[&str],
    flags: &[FlagDef<S>],
    on_unknown: OnUnknown,
    style: Style,
    permute: bool,
) -> Result<ScanResult, Error> {
    scan_with_policy(
        args,
        flags,
        Policy::<Static>::STANDARD,
        on_unknown,
        style,
        permute,
    )
}

/// Scan arguments with command-specific value and numeric policies
#[doc(hidden)]
pub fn scan_with_policy<S: Storage, P: Storage>(
    args: &[&str],
    flags: &[FlagDef<S>],
    policy: Policy<'_, P>,
    on_unknown: OnUnknown,
    style: Style,
    permute: bool,
) -> Result<ScanResult, Error> {
    let config = ScanConfig {
        flags,
        policy,
        on_unknown,
        style,
    };
    let mut result = ScanResult {
        flags: Vec::new(),
        operands: Vec::new(),
        unimplemented: Vec::new(),
    };
    let has_polarity = flags.iter().any(|f| is_polar(&f.kind));
    let gnu = style == Style::Gnu;
    let mut cursor = Cursor::new(args);

    while let Some(arg) = cursor.peek() {
        if process_first_numeric(arg, &mut cursor, &config, &mut result)? {
            continue;
        }
        if process_numeric_operand(arg, &mut cursor, &config, &mut result)? {
            continue;
        }
        if arg == "--" {
            cursor.advance();
            break;
        }
        if gnu && is_long(arg) {
            let operand_count = result.operands.len();
            let spec = arg.strip_prefix("--").unwrap_or_default();
            if let Err(error) = process_long(spec, &mut cursor, &config, &mut result) {
                pass_unknown_long(error, arg, on_unknown, &mut result.operands)?;
            }
            if !permute && result.operands.len() > operand_count {
                break;
            }
            continue;
        }
        match classify(arg, has_polarity) {
            ArgClass::Flags(polarity, chars) => {
                let operand_count = result.operands.len();
                process_cluster(chars, polarity, &mut cursor, &config, &mut result)?;
                if !permute && result.operands.len() > operand_count {
                    break;
                }
            }
            // GNU permutation lets operands pass, and with permute off the first operand ends scanning
            ArgClass::Operand if gnu && permute => {
                result.operands.push(arg.to_owned());
                cursor.advance();
            }
            ArgClass::Operand => break,
        }
    }

    result
        .operands
        .extend(cursor.rest().iter().map(|s| (*s).to_owned()));
    result.flags.retain(|parsed| {
        !flags
            .iter()
            .any(|flag| flag.ch == parsed_char(parsed) && flag.kind == FlagKind::Noop)
    });
    Ok(result)
}

fn pass_unknown_long(
    error: Error,
    arg: &str,
    on_unknown: OnUnknown,
    operands: &mut Vec<String>,
) -> Result<(), Error> {
    if on_unknown == OnUnknown::PassThrough && matches!(error, Error::UnknownFlag(_)) {
        operands.push(arg.to_owned());
        Ok(())
    } else {
        Err(error)
    }
}

#[doc(hidden)]
pub struct Policy<'a, S: Storage> {
    value_rules: &'a [ValueRule<S>],
    numeric_operands: &'a [NumericOperandRule],
    first_numeric_value: Option<char>,
    exact_long: bool,
    equals_only: &'a [char],
    attached_values: &'a [char],
    separated_values: &'a [char],
    prefixed_values: &'a [char],
    exclusive_groups: &'a [ExclusiveRule],
}

impl<S: Storage> Policy<'_, S> {
    const STANDARD: Policy<'static, Static> = Policy {
        value_rules: &[],
        numeric_operands: &[],
        first_numeric_value: None,
        exact_long: false,
        equals_only: &[],
        attached_values: &[],
        separated_values: &[],
        prefixed_values: &[],
        exclusive_groups: &[],
    };

    #[doc(hidden)]
    pub fn from_definition(definition: &CommandDef<S>) -> Policy<'_, S> {
        Policy {
            value_rules: definition.value_rules.as_ref(),
            numeric_operands: definition.numeric_operands.as_ref(),
            first_numeric_value: definition.first_numeric_value,
            exact_long: definition.exact_long,
            equals_only: definition.equals_only.as_ref(),
            attached_values: definition.attached_values.as_ref(),
            separated_values: definition.separated_values.as_ref(),
            prefixed_values: definition.prefixed_values.as_ref(),
            exclusive_groups: definition.exclusive_groups.as_ref(),
        }
    }

    fn value(&self, ch: char) -> Option<&ValueRule<S>> {
        self.value_rules.iter().find(|rule| rule.ch == ch)
    }

    fn requires_equals(&self, ch: char) -> bool {
        self.equals_only.contains(&ch)
    }

    fn requires_attached(&self, ch: char) -> bool {
        self.attached_values.contains(&ch)
    }

    fn requires_separated(&self, ch: char) -> bool {
        self.separated_values.contains(&ch)
    }

    fn accepts_prefix(&self, ch: char) -> bool {
        self.prefixed_values.contains(&ch)
    }

    fn exclusive_group(&self, ch: char) -> Option<u16> {
        self.exclusive_groups
            .iter()
            .find_map(|rule| (rule.ch == ch).then_some(rule.group))
    }
}
