//! Command metadata and the `Command` trait.
//!
//! The derive macro generates implementations of [`Command`], producing
//! static [`CommandDef`] descriptors for introspection and help text.
//!
//! # Help sections
//!
//! Doc comments on the struct are parsed into bash-compatible help sections
//! using two markers: `# Options` and `# Exit Status`.
//!
//! ```rust,ignore
//! /// Summary line.                         → about
//! ///
//! /// Description paragraphs.               → description
//! ///
//! /// # Options                             → auto-generated Options inserted here
//! ///
//! /// Post-options text.                    → extra (after Options)
//! ///
//! /// # Exit Status                         → exit_status header
//! /// Status description.                   → exit_status content
//! ```
//!
//! If `# Options` is absent, auto-generated Options are placed after the
//! description. If `# Exit Status` is absent, no Exit Status section appears.
//!
//! Two optional attributes on `#[command()]`:
//! - `short_doc = "..."` — overrides auto-generated usage in help display
//! - `extra_help("line", ...)` — tab-formatted content (replaces doc extra)

use crate::error::Error;
use crate::parse::{FlagDef, FlagKind, OnUnknown};
use crate::policy::{NumericOperandRule, ValueRule};
use crate::style::Style;

/// Storage used by command metadata
pub trait Storage: 'static {
    /// Text storage
    type Text: AsRef<str> + 'static;
    /// Sequence storage
    type List<T: 'static>: AsRef<[T]>;
}

/// Borrowed static command metadata
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Static {}

impl Storage for Static {
    type Text = &'static str;
    type List<T: 'static> = &'static [T];
}

/// Owned command metadata
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Owned {}

impl Storage for Owned {
    type Text = String;
    type List<T: 'static> = Vec<T>;
}

/// The trait implemented by `#[derive(Command)]` structs.
pub trait Command: Sized {
    /// Static metadata describing this command.
    fn def() -> &'static CommandDef;

    /// Parse from an argument slice.
    ///
    /// # Errors
    ///
    /// Returns a parse error if arguments don't match the definition.
    fn parse(args: &[&str]) -> Result<Self, Error>;
}

/// Static metadata for a command, generated by the derive macro.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    reason = "static config generated by derive"
)]
pub struct CommandDef<S: Storage = Static> {
    /// Command name (e.g., "cd").
    pub name: S::Text,
    /// Short description (first line of doc comment).
    pub about: S::Text,
    /// Override for the auto-generated usage in help display.
    pub short_doc: S::Text,
    /// Parsing style.
    pub style: Style,
    /// How unrecognized flags are handled.
    pub on_unknown: OnUnknown,
    /// Whether options may follow positional operands.
    pub permute: bool,
    /// Declared flags.
    pub flags: S::List<FlagDef<S>>,
    /// Declared positional arguments (in order).
    pub positionals: S::List<PositionalDef<S>>,
    /// Whether a rest-args (`Operands`) field exists.
    pub has_rest: bool,
    /// Missing-value behavior keyed by flag identity.
    pub value_rules: S::List<ValueRule<S>>,
    /// Legacy numeric operand routes.
    pub numeric_operands: S::List<NumericOperandRule>,
    /// First-argument obsolete numeric flag target.
    pub first_numeric_value: Option<char>,
    /// Whether GNU long options require exact names.
    pub exact_long: bool,
    /// Valued long options that require an attached value.
    pub equals_only: S::List<char>,
    /// Generic key-value tags for downstream consumers.
    pub tags: S::List<(S::Text, S::Text)>,
    /// Body paragraphs between summary and Options.
    pub description: S::List<S::Text>,
    /// Content placed after auto-generated Options section.
    pub extra: S::List<S::Text>,
    /// Exit Status section content.
    pub exit_status: S::List<S::Text>,
}

/// Runtime-owned command metadata
pub type OwnedCommandDef = CommandDef<Owned>;

/// Metadata for a positional argument slot.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    reason = "static config generated by derive"
)]
pub struct PositionalDef<S: Storage = Static> {
    /// Field name (used in error messages).
    pub name: S::Text,
    /// Whether the user must provide this argument.
    pub required: bool,
    /// Human-readable description (from doc comment).
    pub desc: S::Text,
}

const INDENT: &str = "    ";

impl<S: Storage> CommandDef<S>
where
    S::Text: AsRef<str>,
    S::List<FlagDef<S>>: AsRef<[FlagDef<S>]>,
    S::List<PositionalDef<S>>: AsRef<[PositionalDef<S>]>,
    S::List<(S::Text, S::Text)>: AsRef<[(S::Text, S::Text)]>,
    S::List<S::Text>: AsRef<[S::Text]>,
{
    /// Command name
    pub fn name(&self) -> &str {
        self.name.as_ref()
    }

    /// Declared flags
    pub fn flags(&self) -> &[FlagDef<S>] {
        self.flags.as_ref()
    }

    /// Generic metadata tags
    pub fn tags(&self) -> &[(S::Text, S::Text)] {
        self.tags.as_ref()
    }

    /// Scan one invocation against this command shape
    ///
    /// # Errors
    ///
    /// Returns an error when the arguments violate the declared shape.
    pub fn scan(&self, args: &[&str]) -> Result<crate::parse::ScanResult, Error> {
        let policy = crate::parse::Policy::new(
            self.value_rules.as_ref(),
            self.numeric_operands.as_ref(),
            self.first_numeric_value,
            self.exact_long,
            self.equals_only.as_ref(),
        );
        crate::parse::scan_with_policy(
            args,
            self.flags(),
            policy,
            self.on_unknown,
            self.style,
            self.permute,
        )
    }

    /// Auto-generate a usage string like `cd [-LP] [dir]`.
    #[must_use]
    pub fn usage(&self) -> String {
        let mut parts = vec![self.name().to_owned()];
        parts.extend(self.flag_usage());
        for p in self.positionals.as_ref() {
            parts.push(if p.required {
                p.name.as_ref().to_owned()
            } else {
                format!("[{}]", p.name.as_ref())
            });
        }
        if self.has_rest {
            parts.push("[args...]".to_owned());
        }
        parts.join(" ")
    }

    /// Flag fragments for the usage line; long-only flags show as `[--long]`.
    fn flag_usage(&self) -> Vec<String> {
        let mut parts = Vec::new();
        let shorts: String = self
            .flags()
            .iter()
            .filter(|f| {
                matches!(f.kind, FlagKind::Bool | FlagKind::Polar | FlagKind::Noop)
                    && !is_synthetic(f.ch)
                    && !f.hidden
            })
            .map(|f| f.ch)
            .collect();
        if !shorts.is_empty() {
            parts.push(format!("[-{shorts}]"));
        }
        for f in self.flags().iter().filter(|f| !f.hidden) {
            let value_name = f.value_name.as_ref();
            let vn = if value_name.is_empty() {
                "ARG"
            } else {
                value_name
            };
            if matches!(f.kind, FlagKind::Value | FlagKind::PolarValue) && !is_synthetic(f.ch) {
                parts.push(format!("[-{} {vn}]", f.ch));
            } else if !f.long.as_ref().is_empty() && is_synthetic(f.ch) {
                let val = if value_name.is_empty() {
                    String::new()
                } else {
                    format!("={value_name}")
                };
                parts.push(format!("[--{}{val}]", f.long.as_ref()));
            }
        }
        parts
    }

    /// Help text in the command's style: bash-builtin for POSIX, GNU for Gnu.
    #[must_use]
    pub fn help(&self) -> String {
        if self.style == Style::Gnu {
            return self.gnu_help();
        }
        let mut out = String::with_capacity(512);

        let short_doc = self.short_doc.as_ref();
        let sd = if short_doc.is_empty() {
            self.usage()
        } else {
            short_doc.to_owned()
        };
        push_line(&mut out, "", &format!("{}: {sd}", self.name()));

        push_line(&mut out, INDENT, self.about.as_ref());

        if !self.description.as_ref().is_empty() {
            push_empty(&mut out);
            for line in self.description.as_ref() {
                push_body(&mut out, line.as_ref());
            }
        }

        let printable: Vec<_> = self
            .flags()
            .iter()
            .filter(|f| {
                !matches!(f.kind, FlagKind::Noop) && !f.desc.as_ref().is_empty() && !f.hidden
            })
            .collect();
        let has_options = !printable.is_empty();
        if has_options {
            push_empty(&mut out);
            push_line(&mut out, INDENT, "Options:");
            for f in &printable {
                push_flag(&mut out, f);
            }
        }

        if !self.extra.as_ref().is_empty() {
            push_empty(&mut out);
            for line in self.extra.as_ref() {
                push_body(&mut out, line.as_ref());
            }
        }

        if !self.exit_status.as_ref().is_empty() {
            push_empty(&mut out);
            push_line(&mut out, INDENT, "Exit Status:");
            for line in self.exit_status.as_ref() {
                push_body(&mut out, line.as_ref());
            }
        }

        out
    }

    /// GNU coreutils-style help: `Usage:` line, about, then `-c, --long` options.
    fn gnu_help(&self) -> String {
        let mut out = String::with_capacity(256);
        let short_doc = self.short_doc.as_ref();
        let usage = if short_doc.is_empty() {
            self.usage()
        } else {
            short_doc.to_owned()
        };
        out.push_str("Usage: ");
        out.push_str(&usage);
        out.push('\n');
        if !self.about.as_ref().is_empty() {
            out.push_str(self.about.as_ref());
            out.push('\n');
        }
        for line in self.description.as_ref() {
            out.push_str(line.as_ref());
            out.push('\n');
        }
        self.push_gnu_options(&mut out);
        for line in self.exit_status.as_ref() {
            out.push_str(line.as_ref());
            out.push('\n');
        }
        out
    }

    /// Append the GNU options block; `--help`/`--version` are always listed.
    fn push_gnu_options(&self, out: &mut String) {
        out.push('\n');
        for f in self.flags().iter().filter(|f| {
            !matches!(f.kind, FlagKind::Noop) && !f.desc.as_ref().is_empty() && !f.hidden
        }) {
            out.push_str(&gnu_flag_line(f));
        }
        if self.flags().iter().any(|flag| flag.ch == 'h') {
            out.push_str("      --help\tdisplay this help and exit\n");
        } else {
            out.push_str("  -h, --help\tdisplay this help and exit\n");
        }
        if self.flags().iter().any(|flag| flag.ch == 'V') {
            out.push_str("      --version\toutput version information and exit\n");
        } else {
            out.push_str("  -V, --version\toutput version information and exit\n");
        }
    }
}

impl CommandDef<Static> {
    /// Copy static metadata into its runtime-owned form
    pub fn into_owned(self) -> OwnedCommandDef {
        OwnedCommandDef {
            name: self.name.to_owned(),
            about: self.about.to_owned(),
            short_doc: self.short_doc.to_owned(),
            style: self.style,
            on_unknown: self.on_unknown,
            permute: self.permute,
            flags: self
                .flags
                .iter()
                .cloned()
                .map(FlagDef::into_owned)
                .collect(),
            positionals: self
                .positionals
                .iter()
                .cloned()
                .map(PositionalDef::into_owned)
                .collect(),
            has_rest: self.has_rest,
            value_rules: self
                .value_rules
                .iter()
                .cloned()
                .map(ValueRule::into_owned)
                .collect(),
            numeric_operands: self.numeric_operands.to_vec(),
            first_numeric_value: self.first_numeric_value,
            exact_long: self.exact_long,
            equals_only: self.equals_only.to_vec(),
            tags: self
                .tags
                .iter()
                .map(|(key, value)| ((*key).to_owned(), (*value).to_owned()))
                .collect(),
            description: self
                .description
                .iter()
                .map(|line| (*line).to_owned())
                .collect(),
            extra: self.extra.iter().map(|line| (*line).to_owned()).collect(),
            exit_status: self
                .exit_status
                .iter()
                .map(|line| (*line).to_owned())
                .collect(),
        }
    }
}

impl PositionalDef<Static> {
    fn into_owned(self) -> PositionalDef<Owned> {
        PositionalDef {
            name: self.name.to_owned(),
            required: self.required,
            desc: self.desc.to_owned(),
        }
    }
}

fn push_line(out: &mut String, indent: &str, text: &str) {
    out.push_str(indent);
    out.push_str(text);
    out.push('\n');
}

fn push_empty(out: &mut String) {
    out.push_str(INDENT);
    out.push('\n');
}

fn push_body(out: &mut String, line: &str) {
    if line.is_empty() {
        push_empty(out);
    } else {
        push_line(out, INDENT, line);
    }
}

fn push_flag<S: Storage>(out: &mut String, f: &FlagDef<S>)
where
    S::Text: AsRef<str>,
{
    let value_name = f.value_name.as_ref();
    let flag_part = if value_name.is_empty() {
        format!("-{}", f.ch)
    } else {
        format!("-{} {value_name}", f.ch)
    };

    let desc = f.desc.as_ref();
    let desc_lines: Vec<&str> = if desc.is_empty() {
        vec![]
    } else {
        desc.split('\n').collect()
    };
    let marker = if f.implemented {
        ""
    } else {
        " (external only)"
    };

    let mut lines = desc_lines.iter();
    if let Some(first) = lines.next() {
        push_line(out, INDENT, &format!("  {flag_part}\t{first}{marker}"));
        for cont in lines {
            push_line(out, INDENT, &format!("\t\t{cont}"));
        }
    } else {
        push_line(out, INDENT, &format!("  {flag_part}{marker}"));
    }
}

/// One GNU option line: `  -c, --long[=VALUE]\tDESC`, or `      --long` when long-only.
fn gnu_flag_line<S: Storage>(f: &FlagDef<S>) -> String
where
    S::Text: AsRef<str>,
{
    let value_name = f.value_name.as_ref();
    let value = if value_name.is_empty() {
        String::new()
    } else {
        format!("={value_name}")
    };
    let long = f.long.as_ref();
    let head = if is_synthetic(f.ch) {
        format!("      --{long}{value}")
    } else if long.is_empty() {
        format!("  -{}", f.ch)
    } else {
        format!("  -{}, --{long}{value}", f.ch)
    };
    let marker = if f.implemented {
        ""
    } else {
        " (external only)"
    };
    format!("{head}\t{}{marker}\n", f.desc.as_ref())
}

/// Long-only flags carry a synthetic identity codepoint (>= U+E000); real
/// short flags are byte-derived (<= U+00FF), so the ranges never overlap.
const fn is_synthetic(ch: char) -> bool {
    ch >= '\u{E000}'
}

#[cfg(test)]
#[expect(clippy::unwrap_used, reason = "tests verify known structure")]
mod tests {
    use super::{CommandDef, OwnedCommandDef, PositionalDef};
    use crate::parse::{FlagDef, FlagKind, OnUnknown};
    use crate::style::Style;

    fn make_def(
        name: &'static str,
        about: &'static str,
        short_doc: &'static str,
        flags: &'static [FlagDef],
        description: &'static [&'static str],
        extra: &'static [&'static str],
        exit_status: &'static [&'static str],
    ) -> CommandDef {
        CommandDef {
            name,
            about,
            short_doc,
            style: Style::Posix,
            on_unknown: OnUnknown::Reject,
            permute: false,
            flags,
            positionals: &[],
            has_rest: false,
            value_rules: &[],
            numeric_operands: &[],
            first_numeric_value: None,
            exact_long: false,
            equals_only: &[],
            tags: &[],
            description,
            extra,
            exit_status,
        }
    }

    // ── Test against real `bash -c 'help alias'` output ────────

    static ALIAS_FLAGS: [FlagDef; 1] = [FlagDef {
        ch: 'p',
        long: "",
        aliases: &[],
        kind: FlagKind::Bool,
        clears: &[],
        desc: "print all defined aliases in a reusable format",
        value_name: "",
        hidden: false,
        implemented: true,
        repeatable: false,
        allow_hyphen_values: true,
    }];

    #[test]
    fn help_alias_matches_bash() {
        let def = make_def(
            "alias",
            "Define or display aliases.",
            "alias [-p] [name[=value] ... ]",
            &ALIAS_FLAGS,
            &[
                "Without arguments, `alias' prints the list of aliases in the reusable",
                "form `alias NAME=VALUE' on standard output.",
                "",
                "Otherwise, an alias is defined for each NAME whose VALUE is given.",
                "A trailing space in VALUE causes the next word to be checked for",
                "alias substitution when the alias is expanded.",
            ],
            &[],
            &[
                "alias returns true unless a NAME is supplied for which no alias has been",
                "defined.",
            ],
        );

        let expected = concat!(
            "alias: alias [-p] [name[=value] ... ]\n",
            "    Define or display aliases.\n",
            "    \n",
            "    Without arguments, `alias' prints the list of aliases in the reusable\n",
            "    form `alias NAME=VALUE' on standard output.\n",
            "    \n",
            "    Otherwise, an alias is defined for each NAME whose VALUE is given.\n",
            "    A trailing space in VALUE causes the next word to be checked for\n",
            "    alias substitution when the alias is expanded.\n",
            "    \n",
            "    Options:\n",
            "      -p\tprint all defined aliases in a reusable format\n",
            "    \n",
            "    Exit Status:\n",
            "    alias returns true unless a NAME is supplied for which no alias has been\n",
            "    defined.\n",
        );
        assert_eq!(def.help(), expected);
    }

    // ── Test against real `bash -c 'help exit'` output ─────────
    // exit has no Options, no Exit Status section

    #[test]
    fn help_exit_matches_bash() {
        let def = make_def(
            "exit",
            "Exit the shell.",
            "exit [n]",
            &[],
            &[
                "Exits the shell with a status of N.  If N is omitted, the exit status",
                "is that of the last command executed.",
            ],
            &[],
            &[],
        );

        let expected = concat!(
            "exit: exit [n]\n",
            "    Exit the shell.\n",
            "    \n",
            "    Exits the shell with a status of N.  If N is omitted, the exit status\n",
            "    is that of the last command executed.\n",
        );
        assert_eq!(def.help(), expected);
    }

    // ── Test against real `bash -c 'help shift'` output ────────
    // shift has no Options but has Exit Status

    #[test]
    fn help_shift_matches_bash() {
        let def = make_def(
            "shift",
            "Shift positional parameters.",
            "shift [n]",
            &[],
            &[
                "Rename the positional parameters $N+1,$N+2 ... to $1,$2 ...  If N is",
                "not given, it is assumed to be 1.",
            ],
            &[],
            &["Returns success unless N is negative or greater than $#."],
        );

        let expected = concat!(
            "shift: shift [n]\n",
            "    Shift positional parameters.\n",
            "    \n",
            "    Rename the positional parameters $N+1,$N+2 ... to $1,$2 ...  If N is\n",
            "    not given, it is assumed to be 1.\n",
            "    \n",
            "    Exit Status:\n",
            "    Returns success unless N is negative or greater than $#.\n",
        );
        assert_eq!(def.help(), expected);
    }

    // ── Test against real `bash -c 'help return'` output ───────

    #[test]
    fn help_return_matches_bash() {
        let def = make_def(
            "return",
            "Return from a shell function.",
            "return [n]",
            &[],
            &[
                "Causes a function or sourced script to exit with the return value",
                "specified by N.  If N is omitted, the return status is that of the",
                "last command executed within the function or script.",
            ],
            &[],
            &["Returns N, or failure if the shell is not executing a function or script."],
        );

        let expected = concat!(
            "return: return [n]\n",
            "    Return from a shell function.\n",
            "    \n",
            "    Causes a function or sourced script to exit with the return value\n",
            "    specified by N.  If N is omitted, the return status is that of the\n",
            "    last command executed within the function or script.\n",
            "    \n",
            "    Exit Status:\n",
            "    Returns N, or failure if the shell is not executing a function or script.\n",
        );
        assert_eq!(def.help(), expected);
    }

    // ── Test multi-line flag descriptions (cd-style) ───────────

    static CD_FLAGS: [FlagDef; 3] = [
        FlagDef {
            ch: 'L',
            long: "",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &['P'],
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
            desc: "force symbolic links to be followed: resolve symbolic\nlinks in DIR after processing instances of `..'",
        },
        FlagDef {
            ch: 'P',
            long: "",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &['L'],
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
            desc: "use the physical directory structure without following\nsymbolic links: resolve symbolic links in DIR before\nprocessing instances of `..'",
        },
        FlagDef {
            ch: 'e',
            long: "",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
            desc: "if the -P option is supplied, and the current working\ndirectory cannot be determined successfully, exit with\na non-zero status",
        },
    ];

    #[test]
    fn help_cd_multiline_flags() {
        let def = make_def(
            "cd",
            "Change the shell working directory.",
            "cd [-L|[-P [-e]]] [-@] [dir]",
            &CD_FLAGS,
            &[
                "Change the current directory to DIR.  The default DIR is the value of the",
                "HOME shell variable. If DIR is \"-\", it is converted to $OLDPWD.",
                "",
                "The variable CDPATH defines the search path for the directory containing",
                "DIR.  Alternative directory names in CDPATH are separated by a colon (:).",
                "A null directory name is the same as the current directory.  If DIR begins",
                "with a slash (/), then CDPATH is not used.",
                "",
                "If the directory is not found, and the shell option `cdable_vars' is set,",
                "the word is assumed to be  a variable name.  If that variable has a value,",
                "its value is used for DIR.",
            ],
            &[
                "The default is to follow symbolic links, as if `-L' were specified.",
                "`..' is processed by removing the immediately previous pathname component",
                "back to a slash or the beginning of DIR.",
            ],
            &[
                "Returns 0 if the directory is changed, and if $PWD is set successfully when",
                "-P is used; non-zero otherwise.",
            ],
        );

        let help = def.help();
        // Verify multi-line flag continuation uses \t\t
        assert!(help.contains("  -L\tforce symbolic links to be followed: resolve symbolic\n"));
        assert!(help.contains("\t\tlinks in DIR after processing instances of `..'\n"));
        // Verify post-Options extra content
        assert!(help.contains("    The default is to follow symbolic links"));
        // Verify Exit Status
        assert!(help.contains("    Exit Status:\n    Returns 0"));
    }

    // ── Test extra_help (echo-style tab-formatted content) ─────

    #[test]
    fn help_with_extra_tab_content() {
        let def = make_def(
            "echo",
            "Write arguments to the standard output.",
            "echo [-neE] [arg ...]",
            &[],
            &[
                "Display the ARGs, separated by a single space character and followed by a",
                "newline, on the standard output.",
            ],
            &[
                "Options:",
                "  -n\tdo not append a newline",
                "  -e\tenable interpretation of the following backslash escapes",
                "  -E\texplicitly suppress interpretation of backslash escapes",
                "",
                "`echo' interprets the following backslash-escaped characters:",
                "  \\a\talert (bell)",
                "  \\b\tbackspace",
            ],
            &["Returns success unless a write error occurs."],
        );

        let help = def.help();
        // First line
        assert!(help.starts_with("echo: echo [-neE] [arg ...]\n"));
        // No auto-generated Options (no flags)
        assert!(!help.contains("    Options:\n    Options:"));
        // Extra content has manual Options
        assert!(help.contains("    Options:\n      -n\t"));
        // Backslash table
        assert!(help.contains("      \\a\talert (bell)\n"));
        // Exit Status
        assert!(help.contains("    Exit Status:\n    Returns success"));
    }

    // ── Test: usage() still works, short_doc only affects help ──

    #[test]
    fn usage_ignores_short_doc() {
        let def = make_def(
            "alias",
            "Define or display aliases.",
            "alias [-p] [name[=value] ... ]",
            &ALIAS_FLAGS,
            &[],
            &[],
            &[],
        );
        assert_eq!(def.usage(), "alias [-p]");
    }

    #[test]
    fn help_falls_back_to_usage_when_no_short_doc() {
        let def = make_def(
            "alias",
            "Define or display aliases.",
            "",
            &ALIAS_FLAGS,
            &[],
            &[],
            &[],
        );
        assert!(def.help().starts_with("alias: alias [-p]\n"));
    }

    // ── Backward compat: existing static constructibility ──────

    #[test]
    fn command_def_is_const_constructible() {
        static DEF: CommandDef = CommandDef {
            name: "test",
            about: "",
            short_doc: "",
            style: Style::Posix,
            on_unknown: OnUnknown::Reject,
            permute: false,
            flags: &[],
            positionals: &[PositionalDef {
                name: "target",
                required: true,
                desc: "",
            }],
            has_rest: false,
            value_rules: &[],
            numeric_operands: &[],
            first_numeric_value: None,
            exact_long: false,
            equals_only: &[],
            tags: &[],
            description: &[],
            extra: &[],
            exit_status: &[],
        };
        assert_eq!(DEF.name, "test");
        assert!(DEF.positionals.first().unwrap().required);
    }

    #[test]
    fn owned_definition_preserves_static_shape() {
        let static_def = make_def(
            "alias",
            "Define or display aliases.",
            "",
            &ALIAS_FLAGS,
            &["Display aliases when no arguments are given."],
            &[],
            &["Returns success unless a name is invalid."],
        );

        let owned: OwnedCommandDef = static_def.clone().into_owned();

        assert_eq!(owned.name(), static_def.name);
        assert_eq!(owned.usage(), static_def.usage());
        assert_eq!(owned.help(), static_def.help());
        assert_eq!(owned.flags().len(), static_def.flags.len());
        assert_eq!(owned.scan(&["-p"]), static_def.scan(&["-p"]));
    }

    // ── GNU help formatting (Style::Gnu) ───────────────────────

    static GNU_FLAGS: [FlagDef; 2] = [
        FlagDef {
            ch: 'a',
            long: "multiple",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            desc: "support multiple arguments and treat each as a NAME",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        },
        FlagDef {
            ch: 's',
            long: "suffix",
            aliases: &[],
            kind: FlagKind::Value,
            clears: &[],
            desc: "remove a trailing SUFFIX; implies -a",
            value_name: "SUFFIX",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        },
    ];

    static CLAIMED_ACTION_FLAGS: [FlagDef; 2] = [
        FlagDef {
            ch: 'h',
            long: "human",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            desc: "human readable",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        },
        FlagDef {
            ch: 'V',
            long: "version-sort",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            desc: "natural version sort",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        },
    ];

    fn gnu_definition(flags: &'static [FlagDef]) -> CommandDef {
        CommandDef {
            name: "sample",
            about: "sample",
            short_doc: "sample [OPTION]...",
            style: Style::Gnu,
            on_unknown: OnUnknown::Reject,
            permute: true,
            flags,
            positionals: &[],
            has_rest: false,
            value_rules: &[],
            numeric_operands: &[],
            first_numeric_value: None,
            exact_long: false,
            equals_only: &[],
            tags: &[],
            description: &[],
            extra: &[],
            exit_status: &[],
        }
    }

    #[test]
    fn gnu_help_renders_usage_about_and_options() {
        let def: CommandDef = CommandDef {
            name: "basename",
            about: "Print NAME with any leading directory components removed",
            short_doc: "basename [-z] NAME [SUFFIX]",
            style: Style::Gnu,
            on_unknown: OnUnknown::Reject,
            permute: true,
            flags: &GNU_FLAGS,
            positionals: &[],
            has_rest: true,
            value_rules: &[],
            numeric_operands: &[],
            first_numeric_value: None,
            exact_long: false,
            equals_only: &[],
            tags: &[],
            description: &[],
            extra: &[],
            exit_status: &[],
        };
        let help = def.help();
        assert!(help.starts_with("Usage: basename [-z] NAME [SUFFIX]\n"));
        assert!(help.contains("Print NAME with any leading directory components removed\n"));
        assert!(
            help.contains(
                "  -a, --multiple\tsupport multiple arguments and treat each as a NAME\n"
            )
        );
        assert!(help.contains("  -s, --suffix=SUFFIX\tremove a trailing SUFFIX; implies -a\n"));
        assert!(help.contains("  -h, --help\tdisplay this help and exit\n"));
        assert!(help.contains("  -V, --version\toutput version information and exit\n"));
    }

    #[test]
    fn gnu_help_footer_present_without_flags() {
        let def: CommandDef = CommandDef {
            name: "true",
            about: "do nothing, successfully",
            short_doc: "true",
            style: Style::Gnu,
            on_unknown: OnUnknown::Reject,
            permute: true,
            flags: &[],
            positionals: &[],
            has_rest: false,
            value_rules: &[],
            numeric_operands: &[],
            first_numeric_value: None,
            exact_long: false,
            equals_only: &[],
            tags: &[],
            description: &[],
            extra: &[],
            exit_status: &[],
        };
        let help = def.help();
        assert!(help.contains("  -h, --help\tdisplay this help and exit\n"));
        assert!(help.contains("  -V, --version\toutput version information and exit\n"));
    }

    #[test]
    fn gnu_help_advertises_unclaimed_short_actions() {
        let definition = gnu_definition(&[]);
        let help = definition.help();
        assert!(help.contains("  -h, --help"));
        assert!(help.contains("  -V, --version"));
    }

    #[test]
    fn gnu_help_omits_claimed_short_actions() {
        let definition = gnu_definition(&CLAIMED_ACTION_FLAGS);
        let help = definition.help();
        assert!(help.contains("      --help"));
        assert!(help.contains("      --version"));
        assert!(!help.contains("  -h, --help"));
        assert!(!help.contains("  -V, --version\t"));
    }

    #[test]
    fn posix_help_stays_bash_formatted() {
        let def = make_def(
            "exit",
            "Exit the shell.",
            "exit [n]",
            &[],
            &["Exits the shell with a status of N."],
            &[],
            &[],
        );
        let help = def.help();
        assert!(help.starts_with("exit: exit [n]\n"));
        assert!(!help.contains("Usage:"));
    }
}
