//! POSIX-style argument parser.
//!
//! Handles: flag bundling (`-abc`), stuck values (`-oval`),
//! separated values (`-o val`), `--` terminator, and `+` polarity.

use crate::error::Error;
use crate::meta::{Owned, Static, Storage};
use crate::polarity::Polarity;
use crate::style::Style;

// ── Public types ────────────────────────────────────────────────

/// How to handle unrecognized flag characters.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[cfg_attr(
    feature = "rkyv",
    derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
)]
#[expect(clippy::exhaustive_enums, reason = "two-state behavioral switch")]
pub enum OnUnknown {
    /// Return an error (standard POSIX behavior).
    #[default]
    Reject,
    /// Treat the entire arg as an operand (echo-style).
    PassThrough,
}

/// Classification of a declared flag for the parser.
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(
    feature = "rkyv",
    derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
)]
#[non_exhaustive]
pub enum FlagKind {
    /// Boolean toggle — presence means true.
    Bool,
    /// Takes a value (next arg or inline remainder).
    Value,
    /// Polarity-aware — tracks `-x` vs `+x`.
    Polar,
    /// Polarity-aware and takes a value.
    PolarValue,
    /// Accepted but ignored (no-op).
    Noop,
}

/// A declared flag that the parser recognizes.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    clippy::struct_excessive_bools,
    reason = "static config generated by derive"
)]
pub struct FlagDef<S: Storage = Static> {
    /// Identity char: the short flag (`-v`), or a private-use codepoint for long-only flags.
    pub ch: char,
    /// The GNU long name without dashes (e.g., "verbose"); empty if short-only.
    pub long: S::Text,
    /// Extra long names resolving to this flag (e.g. "silent" aliasing "quiet").
    pub aliases: S::List<S::Text>,
    /// What kind of flag this is.
    pub kind: FlagKind,
    /// Flags cleared when this one fires (last-wins mutex).
    pub clears: S::List<char>,
    /// Human-readable description (from doc comment).
    pub desc: S::Text,
    /// Value placeholder (empty for bool flags, e.g. "PATH" for valued).
    pub value_name: S::Text,
    /// When true, omit from generated help (still parseable).
    pub hidden: bool,
    /// Whether ecmd may execute this flag internally.
    pub implemented: bool,
    /// Whether this flag accepts more than one occurrence.
    pub repeatable: bool,
    /// Whether a separated value may begin with a hyphen.
    pub allow_hyphen_values: bool,
}

impl FlagDef<Static> {
    pub(crate) fn into_owned(self) -> FlagDef<Owned> {
        FlagDef {
            ch: self.ch,
            long: self.long.to_owned(),
            aliases: self
                .aliases
                .iter()
                .map(|alias| (*alias).to_owned())
                .collect(),
            kind: self.kind,
            clears: self.clears.to_vec(),
            desc: self.desc.to_owned(),
            value_name: self.value_name.to_owned(),
            hidden: self.hidden,
            implemented: self.implemented,
            repeatable: self.repeatable,
            allow_hyphen_values: self.allow_hyphen_values,
        }
    }
}

/// Result of parsing a single flag occurrence.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub enum Parsed {
    /// A boolean flag was set.
    Bool(char),
    /// A valued flag with its argument.
    Value(char, String),
    /// A polarity flag was set.
    Polar(char, Polarity),
    /// A polarity flag with a value.
    PolarValue(char, Polarity, String),
}

/// Output of a successful `scan` call.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(clippy::exhaustive_structs, reason = "result of scan")]
pub struct ScanResult {
    /// Parsed flag occurrences in order.
    pub flags: Vec<Parsed>,
    /// Remaining positional operands.
    pub operands: Vec<String>,
    /// Declared flags that require an external implementation.
    pub unimplemented: Vec<String>,
}

// ── Main entry point ────────────────────────────────────────────

/// Parse arguments according to declared flags.
///
/// # Errors
///
/// Returns an error if an unknown flag is encountered (when
/// `on_unknown` is `Reject`) or a valued flag is missing its argument.
pub fn scan<S: Storage>(
    args: &[&str],
    flags: &[FlagDef<S>],
    on_unknown: OnUnknown,
    style: Style,
    permute: bool,
) -> Result<ScanResult, Error> {
    let mut result = ScanResult {
        flags: Vec::new(),
        operands: Vec::new(),
        unimplemented: Vec::new(),
    };
    let has_polarity = flags.iter().any(|f| is_polar(&f.kind));
    let gnu = style == Style::Gnu;
    let mut cursor = Cursor::new(args);

    while let Some(arg) = cursor.peek() {
        if arg == "--" {
            cursor.advance();
            break;
        }
        if gnu && is_long(arg) {
            let spec = arg.strip_prefix("--").unwrap_or_default();
            process_long(spec, &mut cursor, flags, &mut result)?;
            continue;
        }
        match classify(arg, has_polarity) {
            ArgClass::Flags(polarity, chars) => {
                process_cluster(
                    chars,
                    polarity,
                    &mut cursor,
                    flags,
                    on_unknown,
                    style,
                    &mut result,
                )?;
            },
            // GNU permutation: an operand does not stop option scanning. With
            // `permute` off (POSIX order, e.g. `basename`), the first operand does.
            ArgClass::Operand if gnu && permute => {
                result.operands.push(arg.to_owned());
                cursor.advance();
            },
            ArgClass::Operand => break,
        }
    }

    result
        .operands
        .extend(cursor.rest().iter().map(|s| (*s).to_owned()));
    result.flags.retain(|parsed| {
        !flags
            .iter()
            .any(|flag| flag.ch == parsed_char(parsed) && flag.kind == FlagKind::Noop)
    });
    Ok(result)
}

/// A `--name` or `--name=value` token (but not the bare `--` terminator).
fn is_long(arg: &str) -> bool {
    arg.len() > 2 && arg.starts_with("--")
}

// ── Cursor ──────────────────────────────────────────────────────

struct Cursor<'a> {
    args: &'a [&'a str],
    pos: usize,
}

impl<'a> Cursor<'a> {
    const fn new(args: &'a [&'a str]) -> Self {
        Self { args, pos: 0 }
    }

    fn peek(&self) -> Option<&'a str> {
        self.args.get(self.pos).copied()
    }

    const fn advance(&mut self) {
        self.pos = self.pos.saturating_add(1);
    }

    fn next_value(&mut self, flag_ch: char) -> Result<String, Error> {
        self.advance();
        self.take_next(&format!("-{flag_ch}"))
    }

    fn take_next(&mut self, opt: &str) -> Result<String, Error> {
        let val = self
            .peek()
            .map(ToOwned::to_owned)
            .ok_or_else(|| Error::MissingValue(opt.to_owned()))?;
        self.advance();
        Ok(val)
    }

    fn rest(&self) -> &'a [&'a str] {
        self.args.get(self.pos..).unwrap_or_default()
    }

    fn following(&self) -> Option<&'a str> {
        self.args.get(self.pos.saturating_add(1)).copied()
    }
}

// ── Classification ──────────────────────────────────────────────

const fn is_polar(kind: &FlagKind) -> bool {
    matches!(kind, FlagKind::Polar | FlagKind::PolarValue)
}

enum ArgClass<'a> {
    Flags(Polarity, &'a str),
    Operand,
}

fn classify(arg: &str, has_polarity: bool) -> ArgClass<'_> {
    let Some((&first, rest)) = arg.as_bytes().split_first() else {
        return ArgClass::Operand;
    };
    if rest.is_empty() {
        return ArgClass::Operand;
    }
    let chars = arg.get(1..).unwrap_or_default();
    match first {
        b'-' => ArgClass::Flags(Polarity::On, chars),
        b'+' if has_polarity => ArgClass::Flags(Polarity::Off, chars),
        _ => ArgClass::Operand,
    }
}

fn find_flag<S: Storage>(ch: char, flags: &[FlagDef<S>]) -> Option<&FlagDef<S>> {
    flags.iter().find(|f| f.ch == ch)
}

// ── Cluster processing ──────────────────────────────────────────

fn process_cluster<S: Storage>(
    chars: &str,
    polarity: Polarity,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    on_unknown: OnUnknown,
    style: Style,
    result: &mut ScanResult,
) -> Result<(), Error> {
    if try_prefixed_value(chars, polarity, cursor, flags, style, result)? {
        return Ok(());
    }
    if try_passthrough(
        chars,
        cursor,
        flags,
        on_unknown,
        style,
        &mut result.operands,
    ) {
        return Ok(());
    }
    parse_known_cluster(chars, polarity, cursor, flags, style, result)
}

fn try_prefixed_value<S: Storage>(
    chars: &str,
    polarity: Polarity,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    style: Style,
    result: &mut ScanResult,
) -> Result<bool, Error> {
    let Some((value, ch)) = chars.split_at_checked(chars.len().saturating_sub(1)) else {
        return Ok(false);
    };
    let Some(ch) = ch.chars().next() else {
        return Ok(false);
    };
    if polarity != Polarity::On
        || value.is_empty()
        || !value.bytes().all(|byte| byte.is_ascii_digit())
        || !marker_chars(flags, "prefixed-values").contains(ch)
    {
        return Ok(false);
    }
    let Some(def) = find_flag(ch, flags) else {
        return Ok(false);
    };
    let label = format!("-{ch}");
    reject_conflict(ch, &label, flags, result)?;
    reject_repeat(def, result, &label, style)?;
    result.flags.push(Parsed::Value(ch, value.to_owned()));
    cursor.advance();
    Ok(true)
}

fn try_passthrough<S: Storage>(
    chars: &str,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    on_unknown: OnUnknown,
    style: Style,
    operands: &mut Vec<String>,
) -> bool {
    if on_unknown != OnUnknown::PassThrough {
        return false;
    }
    if !has_unknown_flag(chars, flags, style) {
        return false;
    }
    if let Some(full_arg) = cursor.peek() {
        operands.push(full_arg.to_owned());
    }
    cursor.advance();
    true
}

fn has_unknown_flag<S: Storage>(chars: &str, flags: &[FlagDef<S>], style: Style) -> bool {
    for &b in chars.as_bytes() {
        match find_flag(char::from(b), flags) {
            None if implicit_short_action(char::from(b), style).is_some() => {},
            None => return true,
            Some(def) if matches!(def.kind, FlagKind::Value | FlagKind::PolarValue) => {
                return false;
            },
            _ => {},
        }
    }
    false
}

fn parse_known_cluster<S: Storage>(
    chars: &str,
    polarity: Polarity,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    style: Style,
    result: &mut ScanResult,
) -> Result<(), Error> {
    for (bi, &byte) in chars.as_bytes().iter().enumerate() {
        let ch = char::from(byte);
        let Some(def) = find_flag(ch, flags) else {
            return Err(implicit_short_action(ch, style)
                .unwrap_or_else(|| Error::UnknownFlag(format!("-{ch}"))));
        };
        if !def.implemented {
            result.unimplemented.push(format!("-{ch}"));
        }
        reject_conflict(ch, &format!("-{ch}"), flags, result)?;
        match def.kind {
            FlagKind::Bool => {
                reject_repeat(def, result, &format!("-{ch}"), style)?;
                result.flags.push(Parsed::Bool(ch));
            },
            FlagKind::Noop => {
                reject_repeat(def, result, &format!("-{ch}"), style)?;
                result.flags.push(Parsed::Bool(ch));
            },
            FlagKind::Polar => {
                reject_repeat(def, result, &format!("-{ch}"), style)?;
                result.flags.push(Parsed::Polar(ch, polarity));
            },
            FlagKind::Value | FlagKind::PolarValue => {
                let value = extract_value(chars, bi, cursor, ch, def, flags)?;
                reject_repeat(def, result, &format!("-{ch}"), style)?;
                let parsed = match def.kind {
                    FlagKind::Value => Parsed::Value(ch, value),
                    _ => Parsed::PolarValue(ch, polarity, value),
                };
                result.flags.push(parsed);
                return Ok(());
            },
        }
    }
    cursor.advance();
    Ok(())
}

fn implicit_short_action(ch: char, style: Style) -> Option<Error> {
    if style != Style::Gnu {
        return None;
    }
    match ch {
        'h' => Some(Error::HelpRequested),
        'V' => Some(Error::VersionRequested),
        _ => None,
    }
}

fn extract_value<S: Storage>(
    chars: &str,
    byte_pos: usize,
    cursor: &mut Cursor<'_>,
    flag_ch: char,
    def: &FlagDef<S>,
    flags: &[FlagDef<S>],
) -> Result<String, Error> {
    let after = byte_pos.saturating_add(1);
    let remainder = chars.get(after..).unwrap_or_default();
    if !remainder.is_empty() {
        cursor.advance();
        // clap parity: a single leading `=` is the attached-value separator (`-c=5` → `5`).
        return Ok(remainder.strip_prefix('=').unwrap_or(remainder).to_owned());
    }
    if marker_chars(flags, "attached-values").contains(flag_ch) {
        cursor.advance();
        return Err(Error::MissingValue(format!("-{flag_ch}")));
    }
    if let Some((default, consume_next, any_value)) = optional_value(def.ch, flags) {
        if consume_next
            && cursor
                .following()
                .is_some_and(|value| any_value || is_value(value))
        {
            return cursor.next_value(flag_ch);
        }
        cursor.advance();
        return Ok(default.to_owned());
    }
    let label = format!("-{flag_ch}");
    reject_option_value(cursor.following(), def, flags, &label)?;
    cursor.next_value(flag_ch)
}

fn reject_option_value<S: Storage>(
    value: Option<&str>,
    def: &FlagDef<S>,
    flags: &[FlagDef<S>],
    label: &str,
) -> Result<(), Error> {
    if def.allow_hyphen_values {
        return Ok(());
    }
    let Some(value) = value.filter(|value| value.starts_with('-') && value.len() > 1) else {
        return Ok(());
    };
    if is_declared_option(value, flags) {
        Err(Error::MissingValue(label.to_owned()))
    } else {
        Err(Error::UnknownFlag(value.to_owned()))
    }
}

fn is_declared_option<S: Storage>(value: &str, flags: &[FlagDef<S>]) -> bool {
    if value == "--" {
        return true;
    }
    if let Some(name) = value.strip_prefix("--") {
        let name = name.split_once('=').map_or(name, |(name, _)| name);
        return !matches!(resolve_long(name, flags), LongMatch::Unknown);
    }
    value
        .strip_prefix('-')
        .and_then(|cluster| cluster.chars().next())
        .is_some_and(|ch| find_flag(ch, flags).is_some() || matches!(ch, 'h' | 'V'))
}

// ── Long-option processing (GNU style) ──────────────────────────

/// Outcome of resolving a long-option name against the declared flags.
enum LongMatch<'a, S: Storage> {
    Flag(&'a FlagDef<S>),
    Help,
    Version,
    Ambiguous,
    Unknown,
}

/// Parse one `--name` / `--name=value` token. Cursor is on that token.
fn process_long<S: Storage>(
    spec: &str,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    result: &mut ScanResult,
) -> Result<(), Error> {
    let (name, inline) = spec
        .split_once('=')
        .map_or((spec, None), |(n, v)| (n, Some(v)));
    cursor.advance();
    match resolve_long(name, flags) {
        LongMatch::Flag(def) => apply_long(def, name, inline, cursor, flags, result),
        LongMatch::Help | LongMatch::Version if inline.is_some() => {
            Err(Error::UnexpectedValue(format!("--{name}")))
        },
        LongMatch::Help => Err(Error::HelpRequested),
        LongMatch::Version => Err(Error::VersionRequested),
        LongMatch::Ambiguous => Err(Error::AmbiguousOption(format!("--{name}"))),
        LongMatch::Unknown => Err(Error::UnknownFlag(format!("--{name}"))),
    }
}

/// Record a resolved long flag, pulling a value from `=inline` or the next arg.
fn apply_long<S: Storage>(
    def: &FlagDef<S>,
    name: &str,
    inline: Option<&str>,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    result: &mut ScanResult,
) -> Result<(), Error> {
    if !def.implemented {
        result.unimplemented.push(format!("--{name}"));
    }
    reject_conflict(def.ch, &format!("--{name}"), flags, result)?;
    match def.kind {
        FlagKind::Noop => {
            reject_repeat(def, result, &format!("--{name}"), Style::Gnu)?;
            result.flags.push(Parsed::Bool(def.ch));
            Ok(())
        },
        FlagKind::Bool | FlagKind::Polar => apply_long_flag(def, name, inline, result),
        FlagKind::Value | FlagKind::PolarValue => {
            apply_long_value(def, name, inline, cursor, flags, result)
        },
    }
}

fn reject_conflict<S: Storage>(
    ch: char,
    label: &str,
    flags: &[FlagDef<S>],
    result: &ScanResult,
) -> Result<(), Error> {
    let groups = flags
        .iter()
        .filter_map(|flag| flag.long.as_ref().strip_prefix("\0exclusive-flags:"));
    for group in groups.filter(|group| group.contains(ch)) {
        let current_group = group.split('|').find(|category| category.contains(ch));
        let previous = result.flags.iter().map(parsed_char).find(|prior| {
            group.contains(*prior)
                && current_group.is_none_or(|category| !category.contains(*prior))
        });
        if let Some(previous) = previous {
            return Err(Error::ConflictingFlags {
                current: label.to_owned(),
                previous: format!("-{previous}"),
            });
        }
    }
    Ok(())
}

fn marker_chars<S: Storage>(flags: &[FlagDef<S>], name: &str) -> String {
    let prefix = format!("\0{name}:");
    flags
        .iter()
        .find_map(|flag| flag.long.as_ref().strip_prefix(&prefix))
        .unwrap_or_default()
        .to_owned()
}

fn reject_repeat<S: Storage>(
    def: &FlagDef<S>,
    result: &ScanResult,
    label: &str,
    style: Style,
) -> Result<(), Error> {
    if style != Style::Gnu
        || def.repeatable
        || !result.flags.iter().any(|flag| parsed_char(flag) == def.ch)
    {
        return Ok(());
    }
    Err(Error::RepeatedFlag(label.to_owned()))
}

const fn parsed_char(parsed: &Parsed) -> char {
    match parsed {
        Parsed::Bool(ch)
        | Parsed::Value(ch, _)
        | Parsed::Polar(ch, _)
        | Parsed::PolarValue(ch, _, _) => *ch,
    }
}

/// A long bool/polar flag: presence sets it; an inline `=value` is an error.
fn apply_long_flag<S: Storage>(
    def: &FlagDef<S>,
    name: &str,
    inline: Option<&str>,
    result: &mut ScanResult,
) -> Result<(), Error> {
    if inline.is_some() {
        return Err(Error::UnexpectedValue(format!("--{name}")));
    }
    reject_repeat(def, result, &format!("--{name}"), Style::Gnu)?;
    result.flags.push(if matches!(def.kind, FlagKind::Bool) {
        Parsed::Bool(def.ch)
    } else {
        Parsed::Polar(def.ch, Polarity::On)
    });
    Ok(())
}

/// A long value flag: value comes from `=inline` or the next token.
fn apply_long_value<S: Storage>(
    def: &FlagDef<S>,
    name: &str,
    inline: Option<&str>,
    cursor: &mut Cursor<'_>,
    flags: &[FlagDef<S>],
    result: &mut ScanResult,
) -> Result<(), Error> {
    if inline.is_none() && equals_only(name, flags) {
        return Err(Error::UnknownFlag(format!("--{name}")));
    }
    // GNU getopt_long parity: a value flag consumes the next token even when it looks like an option.
    let value = if let Some(value) = inline {
        value.to_owned()
    } else if let Some((default, consume_next, any_value)) = optional_value(def.ch, flags) {
        if consume_next
            && cursor
                .peek()
                .is_some_and(|value| any_value || is_value(value))
        {
            cursor.take_next(&format!("--{name}"))?
        } else {
            default.to_owned()
        }
    } else {
        let label = format!("--{name}");
        reject_option_value(cursor.peek(), def, flags, &label)?;
        cursor.take_next(&label)?
    };
    reject_repeat(def, result, &format!("--{name}"), Style::Gnu)?;
    result.flags.push(if matches!(def.kind, FlagKind::Value) {
        Parsed::Value(def.ch, value)
    } else {
        Parsed::PolarValue(def.ch, Polarity::On, value)
    });
    Ok(())
}

fn optional_value<S: Storage>(ch: char, flags: &[FlagDef<S>]) -> Option<(&str, bool, bool)> {
    flags.iter().find_map(|flag| {
        let text = flag.long.as_ref();
        let (marker, consume_next, any_value) = text
            .strip_prefix("\0optional-value:")
            .map(|marker| (marker, false, false))
            .or_else(|| {
                text.strip_prefix("\0optional-next-value:")
                    .map(|marker| (marker, true, false))
            })
            .or_else(|| {
                text.strip_prefix("\0optional-any-next-value:")
                    .map(|marker| (marker, true, true))
            })?;
        let (encoded, default) = marker.split_once(':')?;
        (encoded.chars().next() == Some(ch)).then_some((default, consume_next, any_value))
    })
}

fn is_value(value: &str) -> bool {
    value == "-" || !value.starts_with('-')
}

fn equals_only<S: Storage>(name: &str, flags: &[FlagDef<S>]) -> bool {
    let marker = format!("\0equals-only:{name}");
    flags
        .iter()
        .any(|flag| flag.hidden && flag.long.as_ref() == marker)
}

/// Exact match wins; otherwise fall back to unambiguous-prefix inference.
fn resolve_long<'a, S: Storage>(name: &str, flags: &'a [FlagDef<S>]) -> LongMatch<'a, S> {
    if !name.is_empty()
        && let Some(def) = flags.iter().find(|f| {
            f.long.as_ref() == name
                || f.aliases
                    .as_ref()
                    .iter()
                    .any(|alias| alias.as_ref() == name)
        })
    {
        return LongMatch::Flag(def);
    }
    match name {
        "help" => LongMatch::Help,
        "version" => LongMatch::Version,
        _ if exact_long_names(flags) => LongMatch::Unknown,
        _ => infer_long(name, flags),
    }
}

fn exact_long_names<S: Storage>(flags: &[FlagDef<S>]) -> bool {
    flags
        .iter()
        .any(|flag| flag.hidden && flag.long.as_ref() == "\0exact-long")
}

/// Every long name a flag answers to: its primary long plus any aliases.
fn long_names<S: Storage>(flag: &FlagDef<S>) -> impl Iterator<Item = &str> {
    core::iter::once(flag.long.as_ref())
        .chain(flag.aliases.as_ref().iter().map(AsRef::as_ref))
        .filter(|n| !n.is_empty())
}

/// Collect every declared long (plus reserved help/version) prefixed by `name`.
fn infer_long<'a, S: Storage>(name: &str, flags: &'a [FlagDef<S>]) -> LongMatch<'a, S> {
    if name.is_empty() {
        return LongMatch::Unknown;
    }
    let mut found = LongMatch::Unknown;
    let mut count = 0_u32;
    for def in flags {
        // A flag matched by several of its own names (long + alias) still counts once.
        if long_names(def).any(|n| n.starts_with(name)) {
            found = LongMatch::Flag(def);
            count = count.saturating_add(1);
        }
    }
    for (reserved, hit) in [("help", LongMatch::Help), ("version", LongMatch::Version)] {
        // A flag that owns this exact long name shadows the reserved option.
        if reserved.starts_with(name) && !flags.iter().any(|f| long_names(f).any(|n| n == reserved))
        {
            found = hit;
            count = count.saturating_add(1);
        }
    }
    match count {
        1 => found,
        0 => LongMatch::Unknown,
        _ => LongMatch::Ambiguous,
    }
}

#[cfg(test)]
#[expect(clippy::unwrap_used, reason = "tests verify success paths")]
mod tests {
    use pretty_assertions::assert_eq;

    use super::{FlagDef, FlagKind, OnUnknown, Parsed, scan};
    use crate::error::Error;
    use crate::meta::Static;
    use crate::polarity::Polarity;
    use crate::style::Style;

    fn bool_flag(ch: char) -> FlagDef {
        FlagDef {
            ch,
            kind: FlagKind::Bool,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    fn value_flag(ch: char) -> FlagDef {
        FlagDef {
            ch,
            kind: FlagKind::Value,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    fn polar_flag(ch: char) -> FlagDef {
        FlagDef {
            ch,
            kind: FlagKind::Polar,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    fn noop_flag(ch: char) -> FlagDef {
        FlagDef {
            ch,
            kind: FlagKind::Noop,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    #[test]
    fn empty_args_returns_empty() {
        let r = scan::<Static>(&[], &[], OnUnknown::Reject, Style::Posix, true).unwrap();
        assert!(r.flags.is_empty());
        assert!(r.operands.is_empty());
    }

    #[test]
    fn single_bool_flag() {
        let flags = [bool_flag('v')];
        let r = scan(&["-v"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('v')]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn bundled_bool_flags() {
        let flags = [bool_flag('a'), bool_flag('b'), bool_flag('c')];
        let r = scan(&["-abc"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(
            r.flags,
            [Parsed::Bool('a'), Parsed::Bool('b'), Parsed::Bool('c'),]
        );
    }

    #[test]
    fn double_dash_terminates_flags() {
        let flags = [bool_flag('v')];
        let r = scan(&["--", "-v"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert!(r.flags.is_empty());
        assert_eq!(r.operands, ["-v"]);
    }

    #[test]
    fn operands_after_flags() {
        let flags = [bool_flag('v')];
        let r = scan(
            &["-v", "file.txt"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Bool('v')]);
        assert_eq!(r.operands, ["file.txt"]);
    }

    #[test]
    fn valued_flag_separate() {
        let flags = [value_flag('o')];
        let r = scan(
            &["-o", "file"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "file".into())]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn valued_flag_separate_with_trailing() {
        let flags = [value_flag('o')];
        let r = scan(
            &["-o", "file", "rest"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "file".into())]);
        assert_eq!(r.operands, ["rest"]);
    }

    #[test]
    fn valued_flag_stuck() {
        let flags = [value_flag('o')];
        let r = scan(&["-ofile"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "file".into())]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn valued_flag_stuck_strips_equals_separator() {
        let flags = [value_flag('o')];
        let r = scan(&["-o=file"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "file".into())]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn valued_flag_stuck_strips_only_one_equals() {
        let flags = [value_flag('o')];
        let r = scan(&["-o==file"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "=file".into())]);
    }

    #[test]
    fn valued_flag_stuck_bare_equals_is_empty_value() {
        let flags = [value_flag('o')];
        let r = scan(&["-o="], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', String::new())]);
    }

    #[test]
    fn valued_flag_missing_arg_errors() {
        let flags = [value_flag('o')];
        let r = scan(&["-o"], &flags, OnUnknown::Reject, Style::Posix, true);
        assert!(matches!(r, Err(Error::MissingValue(_))));
    }

    #[test]
    fn bundled_bool_then_valued() {
        let flags = [bool_flag('v'), value_flag('o')];
        let r = scan(
            &["-vo", "file"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(
            r.flags,
            [Parsed::Bool('v'), Parsed::Value('o', "file".into()),]
        );
        assert!(r.operands.is_empty());
    }

    #[test]
    fn bundled_bool_then_valued_stuck() {
        let flags = [bool_flag('v'), value_flag('o')];
        let r = scan(&["-vofile"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(
            r.flags,
            [Parsed::Bool('v'), Parsed::Value('o', "file".into()),]
        );
        assert!(r.operands.is_empty());
    }

    #[test]
    fn multiple_valued_flags_in_sequence() {
        let flags = [value_flag('o'), value_flag('d')];
        let r = scan(
            &["-o", "out", "-d", "dir"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(
            r.flags,
            [
                Parsed::Value('o', "out".into()),
                Parsed::Value('d', "dir".into()),
            ]
        );
        assert!(r.operands.is_empty());
    }

    #[test]
    fn unknown_flag_errors() {
        let flags = [bool_flag('v')];
        let r = scan(&["-x"], &flags, OnUnknown::Reject, Style::Posix, true);
        assert!(matches!(r, Err(Error::UnknownFlag(_))));
    }

    #[test]
    fn gnu_implicit_short_help_and_version_are_actions() {
        for (arg, expected) in [
            ("-h", Error::HelpRequested),
            ("-V", Error::VersionRequested),
        ] {
            let result = scan::<Static>(&[arg], &[], OnUnknown::Reject, Style::Gnu, true);
            assert_eq!(result.unwrap_err(), expected);
        }
    }

    #[test]
    fn gnu_reserved_actions_reject_inline_values() {
        for option in ["--help=value", "--version=value"] {
            let result = scan::<Static>(&[option], &[], OnUnknown::Reject, Style::Gnu, true);
            let name = option.split_once('=').unwrap().0.to_owned();
            assert_eq!(result.unwrap_err(), Error::UnexpectedValue(name));
        }
    }

    #[test]
    fn declared_gnu_short_help_and_version_characters_win() {
        let flags = [bool_flag('h'), bool_flag('V')];
        let result = scan(&["-hV"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(result.flags, [Parsed::Bool('h'), Parsed::Bool('V')]);
    }

    #[test]
    fn posix_does_not_add_implicit_short_actions() {
        let result = scan::<Static>(&["-h"], &[], OnUnknown::Reject, Style::Posix, true);
        assert_eq!(result.unwrap_err(), Error::UnknownFlag("-h".to_owned()));
    }

    #[test]
    fn passthrough_unknown_becomes_operand() {
        let flags = [bool_flag('n')];
        let r = scan(
            &["-nea"],
            &flags,
            OnUnknown::PassThrough,
            Style::Posix,
            true,
        )
        .unwrap();
        assert!(r.flags.is_empty());
        assert_eq!(r.operands, ["-nea"]);
    }

    #[test]
    fn passthrough_all_known_still_parses() {
        let flags = [bool_flag('n'), bool_flag('e')];
        let r = scan(
            &["-ne", "hello"],
            &flags,
            OnUnknown::PassThrough,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Bool('n'), Parsed::Bool('e')]);
        assert_eq!(r.operands, ["hello"]);
    }

    #[test]
    fn passthrough_first_char_unknown() {
        let flags = [bool_flag('n')];
        let r = scan(
            &["-xyz", "rest"],
            &flags,
            OnUnknown::PassThrough,
            Style::Posix,
            true,
        )
        .unwrap();
        assert!(r.flags.is_empty());
        assert_eq!(r.operands, ["-xyz", "rest"]);
    }

    #[test]
    fn passthrough_value_flag_stuck_still_parses() {
        let flags = [value_flag('o')];
        let r = scan(
            &["-ofile"],
            &flags,
            OnUnknown::PassThrough,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('o', "file".into())]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn polarity_on() {
        let flags = [polar_flag('x')];
        let r = scan(&["-x"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Polar('x', Polarity::On)]);
    }

    #[test]
    fn polarity_off() {
        let flags = [polar_flag('x')];
        let r = scan(&["+x"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Polar('x', Polarity::Off)]);
    }

    #[test]
    fn plus_prefix_only_when_polarity_flags_exist() {
        let flags = [bool_flag('x')];
        let r = scan(&["+x"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.operands, ["+x"]);
    }

    #[test]
    fn noop_flag_accepted_silently() {
        let flags = [bool_flag('r'), noop_flag('e')];
        let r = scan(&["-re"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('r')]);
    }

    #[test]
    fn noop_flag_repetition_is_rejected_in_gnu_style() {
        let flags = [noop_flag('f')];
        let error = scan(&["-f", "-f"], &flags, OnUnknown::Reject, Style::Gnu, true)
            .expect_err("a scalar noop may occur once");
        assert_eq!(error, Error::RepeatedFlag("-f".to_owned()));
    }

    #[test]
    fn bare_dash_is_operand() {
        let flags = [bool_flag('v')];
        let r = scan(&["-"], &flags, OnUnknown::Reject, Style::Posix, true).unwrap();
        assert_eq!(r.operands, ["-"]);
    }

    #[test]
    fn multiple_flag_groups() {
        let flags = [bool_flag('a'), bool_flag('b')];
        let r = scan(
            &["-a", "-b", "file"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a'), Parsed::Bool('b')]);
        assert_eq!(r.operands, ["file"]);
    }

    #[test]
    fn polar_value_on() {
        let flags: [FlagDef; 1] = [FlagDef {
            ch: 'o',
            kind: FlagKind::PolarValue,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }];
        let r = scan(
            &["-o", "errexit"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(
            r.flags,
            [Parsed::PolarValue('o', Polarity::On, "errexit".into())]
        );
        assert!(r.operands.is_empty());
    }

    #[test]
    fn polar_value_off() {
        let flags: [FlagDef; 1] = [FlagDef {
            ch: 'o',
            kind: FlagKind::PolarValue,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }];
        let r = scan(
            &["+o", "verbose"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(
            r.flags,
            [Parsed::PolarValue('o', Polarity::Off, "verbose".into())]
        );
        assert!(r.operands.is_empty());
    }

    #[test]
    fn polar_value_stuck() {
        let flags: [FlagDef; 1] = [FlagDef {
            ch: 'o',
            kind: FlagKind::PolarValue,
            long: "",
            aliases: &[],
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }];
        let r = scan(
            &["-oerrexit"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap();
        assert_eq!(
            r.flags,
            [Parsed::PolarValue('o', Polarity::On, "errexit".into())]
        );
        assert!(r.operands.is_empty());
    }

    // ── GNU long options (Style::Gnu) ───────────────────────────

    fn long_bool(ch: char, long: &'static str) -> FlagDef {
        FlagDef {
            ch,
            long,
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    fn long_value(ch: char, long: &'static str) -> FlagDef {
        FlagDef {
            ch,
            long,
            aliases: &[],
            kind: FlagKind::Value,
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    #[test]
    fn gnu_exact_long_bool() {
        let flags = [long_bool('a', "multiple")];
        let r = scan(&["--multiple"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a')]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn gnu_long_value_inline() {
        let flags = [long_value('s', "suffix")];
        let r = scan(
            &["--suffix=.txt"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('s', ".txt".into())]);
    }

    #[test]
    fn gnu_long_value_separated() {
        let flags = [long_value('s', "suffix")];
        let r = scan(
            &["--suffix", ".txt"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('s', ".txt".into())]);
    }

    #[test]
    fn gnu_empty_inline_value_is_allowed() {
        let flags = [long_value('s', "suffix")];
        let r = scan(&["--suffix="], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('s', String::new())]);
    }

    #[test]
    fn gnu_prefix_inference_resolves_unambiguous() {
        let flags = [long_bool('a', "multiple")];
        let r = scan(&["--mult"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a')]);
    }

    #[test]
    fn gnu_prefix_ambiguous_is_error() {
        let flags = [long_bool('v', "verbose")];
        // "--ver" matches both "verbose" and the reserved "version".
        let e = scan(&["--ver"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::AmbiguousOption("--ver".into()));
    }

    #[test]
    fn gnu_exact_match_beats_prefix() {
        let flags = [long_bool('a', "no"), long_bool('b', "nonsense")];
        let r = scan(&["--no"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a')]);
    }

    #[test]
    fn gnu_bool_rejects_inline_value() {
        let flags = [long_bool('a', "multiple")];
        let e = scan(
            &["--multiple=x"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap_err();
        assert_eq!(e, Error::UnexpectedValue("--multiple".into()));
    }

    #[test]
    fn gnu_permutes_flags_after_operands() {
        let flags = [long_bool('a', "multiple"), long_bool('z', "zero")];
        let r = scan(
            &["one", "--multiple", "two", "--zero"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a'), Parsed::Bool('z')]);
        assert_eq!(r.operands, ["one", "two"]);
    }

    #[test]
    fn gnu_short_flags_still_bundle() {
        let flags = [long_bool('a', "multiple"), long_bool('z', "zero")];
        let r = scan(&["-az"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('a'), Parsed::Bool('z')]);
    }

    #[test]
    fn gnu_short_value_separated_still_works() {
        let flags = [long_value('s', "suffix")];
        let r = scan(&["-s", ".bak"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('s', ".bak".into())]);
    }

    #[test]
    fn gnu_help_is_signalled() {
        let e = scan::<Static>(&["--help"], &[], OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::HelpRequested);
    }

    #[test]
    fn gnu_version_is_signalled() {
        let e =
            scan::<Static>(&["--version"], &[], OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::VersionRequested);
    }

    #[test]
    fn gnu_help_prefix_infers() {
        let e = scan::<Static>(&["--hel"], &[], OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::HelpRequested);
    }

    #[test]
    fn gnu_unknown_long_is_error() {
        let e = scan::<Static>(&["--bogus"], &[], OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::UnknownFlag("--bogus".into()));
    }

    #[test]
    fn gnu_long_value_missing_errors() {
        let flags = [long_value('s', "suffix")];
        let e = scan(&["--suffix"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::MissingValue("--suffix".into()));
    }

    #[test]
    fn gnu_empty_long_name_is_unknown() {
        let e = scan::<Static>(&["--=x"], &[], OnUnknown::Reject, Style::Gnu, true).unwrap_err();
        assert_eq!(e, Error::UnknownFlag("--".into()));
    }

    #[test]
    fn gnu_value_flag_swallows_optionlike_next() {
        // getopt_long parity: --suffix consumes the following --zero as its value.
        let flags = [long_value('s', "suffix"), long_bool('z', "zero")];
        let r = scan(
            &["--suffix", "--zero"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Value('s', "--zero".into())]);
        assert!(r.operands.is_empty());
    }

    #[test]
    fn gnu_real_help_flag_shadows_reserved() {
        let flags = [long_bool('h', "help")];
        let r = scan(&["--help"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('h')]);
        // `--hel` is not ambiguous: the declared "help" flag shadows the reserved signal.
        let r2 = scan(&["--hel"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r2.flags, [Parsed::Bool('h')]);
    }

    #[test]
    fn gnu_exact_valued_beats_prefix() {
        let flags = [long_value('a', "max"), long_value('b', "maximum")];
        let r = scan(&["--max=5"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Value('a', "5".into())]);
    }

    #[test]
    fn gnu_double_dash_still_terminates() {
        let flags = [long_bool('a', "multiple")];
        let r = scan(
            &["--", "--multiple"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert!(r.flags.is_empty());
        assert_eq!(r.operands, ["--multiple"]);
    }

    #[test]
    fn gnu_no_permute_stops_at_first_operand() {
        // With permute=false (POSIX order, e.g. basename), the first operand
        // ends option scanning; later `-z`/`--zero` become operands.
        let flags = [long_bool('z', "zero")];
        let r = scan(
            &["foo", "-z", "--zero"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            false,
        )
        .unwrap();
        assert!(r.flags.is_empty());
        assert_eq!(r.operands, ["foo", "-z", "--zero"]);
    }

    #[test]
    fn gnu_permute_still_collects_flags_after_operands() {
        // permute=true keeps GNU permutation (flags recognized after operands).
        let flags = [long_bool('z', "zero")];
        let r = scan(&["foo", "-z"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('z')]);
        assert_eq!(r.operands, ["foo"]);
    }

    #[test]
    fn posix_never_parses_double_dash_word_as_long() {
        // Bash/POSIX mode must not gain GNU long-option behavior.
        let flags = [long_bool('a', "multiple")];
        let e = scan(
            &["--multiple"],
            &flags,
            OnUnknown::Reject,
            Style::Posix,
            true,
        )
        .unwrap_err();
        assert_eq!(e, Error::UnknownFlag("--".into()));
    }

    fn aliased_bool(ch: char, long: &'static str, aliases: &'static [&'static str]) -> FlagDef {
        FlagDef {
            ch,
            long,
            aliases,
            kind: FlagKind::Bool,
            clears: &[],
            desc: "",
            value_name: "",
            hidden: false,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }
    }

    #[test]
    fn gnu_alias_resolves_to_flag() {
        let flags = [aliased_bool('q', "quiet", &["silent"])];
        let r = scan(&["--silent"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('q')]);
    }

    #[test]
    fn gnu_alias_prefix_infers() {
        let flags = [aliased_bool('q', "quiet", &["silent"])];
        let r = scan(&["--si"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('q')]);
        let r2 = scan(&["--s"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r2.flags, [Parsed::Bool('q')]);
    }

    #[test]
    fn gnu_alias_and_long_prefix_counts_flag_once() {
        // "--qu" matches the long "quiet"; the flag must not register as ambiguous
        // just because it also owns the "silent" alias.
        let flags = [aliased_bool('q', "quiet", &["silent"])];
        let r = scan(&["--qu"], &flags, OnUnknown::Reject, Style::Gnu, true).unwrap();
        assert_eq!(r.flags, [Parsed::Bool('q')]);
    }

    #[test]
    fn gnu_hidden_flag_still_parses() {
        let flags: [FlagDef; 1] = [FlagDef {
            ch: '\u{E000}',
            long: "presume-input-pipe",
            aliases: &[],
            kind: FlagKind::Bool,
            clears: &[],
            desc: "",
            value_name: "",
            hidden: true,
            implemented: true,
            repeatable: false,
            allow_hyphen_values: true,
        }];
        let r = scan(
            &["--presume-input-pipe"],
            &flags,
            OnUnknown::Reject,
            Style::Gnu,
            true,
        )
        .unwrap();
        assert_eq!(r.flags, [Parsed::Bool('\u{E000}')]);
    }
}
