//! Command-specific argument parsing policy

use crate::meta::{Owned, Static, Storage};

/// How a valued flag behaves when no value is attached
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(
    feature = "rkyv",
    derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
)]
#[non_exhaustive]
pub enum ValueMode {
    /// Use the default and leave the next argument untouched
    AttachedOrDefault,
    /// Consume a following operand or use the default
    NextOrDefault,
    /// Consume a following numeric value or use the default
    NumericNextOrDefault,
    /// Use the default only for an exact short option
    ExactShortDefault,
}

/// Missing-value behavior for one declared flag
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    reason = "static config generated by derive"
)]
pub struct ValueRule<S: Storage = Static> {
    /// Flag identity
    pub ch: char,
    /// Missing-value behavior
    pub mode: ValueMode,
    /// Value supplied by the policy
    pub default: S::Text,
}

impl ValueRule<Static> {
    pub(crate) fn into_owned(self) -> ValueRule<Owned> {
        ValueRule {
            ch: self.ch,
            mode: self.mode,
            default: self.default.to_owned(),
        }
    }
}

/// Legacy numeric operand routed into a valued field
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[cfg_attr(
    feature = "rkyv",
    derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
)]
#[expect(
    clippy::exhaustive_structs,
    reason = "static config generated by derive"
)]
pub struct NumericOperandRule {
    /// Flag identity
    pub ch: char,
    /// Operand prefix
    pub prefix: char,
}
