[package]
name = "ecmd-derive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Derive macro for the ecmd argument parser"
readme = "README.md"
keywords = ["cli", "argument", "parser", "derive"]
categories = ["command-line-interface"]
include = ["src/**/*.rs", "Cargo.toml", "LICENSE", "README.md"]

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[dev-dependencies]
ecmd = { path = "../lib" }
trybuild.workspace = true

[lints]
workspace = true
