//! Command metadata and the `Command` trait

use crate::error::Error;
use crate::parse::{FlagDef, OnUnknown};
use crate::policy::{ExclusiveRule, NumericOperandRule, ValueRule};
use crate::style::{HelpStyle, Style};

mod owned;

/// Storage used by command metadata
pub trait Storage: 'static {
    /// Text storage
    type Text: AsRef<str> + 'static;
    /// Sequence storage
    type List<T: 'static>: AsRef<[T]>;
}

/// Borrowed static command metadata
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Static {}

impl Storage for Static {
    type Text = &'static str;
    type List<T: 'static> = &'static [T];
}

/// Owned command metadata
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum Owned {}

impl Storage for Owned {
    type Text = String;
    type List<T: 'static> = Vec<T>;
}

/// The trait implemented by `#[derive(Command)]` structs.
pub trait Command: Sized {
    /// Static metadata describing this command.
    fn def() -> &'static CommandDef;

    /// Parse one argument slice into the command
    fn parse(args: &[&str]) -> Result<Self, Error>;
}

/// Static metadata for a command, generated by the derive macro.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    clippy::struct_excessive_bools,
    reason = "static config generated by derive"
)]
pub struct CommandDef<S: Storage = Static> {
    /// Command name (e.g., "cd").
    pub name: S::Text,
    /// Short description (first line of doc comment).
    pub about: S::Text,
    /// Override for the auto-generated usage in help display.
    pub short_doc: S::Text,
    /// Parsing style.
    pub style: Style,
    /// Help dialect rendered by [`CommandDef::help`].
    pub help_style: HelpStyle,
    /// How unrecognized flags are handled.
    pub on_unknown: OnUnknown,
    /// Whether options may follow positional operands.
    pub permute: bool,
    /// Declared flags.
    pub flags: S::List<FlagDef<S>>,
    /// Declared positional arguments (in order).
    pub positionals: S::List<PositionalDef<S>>,
    /// Whether a rest-args (`Operands`) field exists.
    pub has_rest: bool,
    /// Label for the rest slot in help; `args` when empty.
    pub rest_label: S::Text,
    /// Whether the rest slot is omitted from generated help.
    pub rest_hidden: bool,
    /// Description shown for the rest slot.
    pub rest_desc: S::Text,
    /// Value the rest slot reports when it is empty; none when empty.
    pub rest_default: S::Text,
    /// Whether the rest slot shows as required.
    pub rest_required: bool,
    /// Missing-value behavior keyed by flag identity.
    pub value_rules: S::List<ValueRule<S>>,
    /// Legacy numeric operand routes.
    pub numeric_operands: S::List<NumericOperandRule>,
    /// First-argument obsolete numeric flag target.
    pub first_numeric_value: Option<char>,
    /// Whether GNU long options require exact names.
    pub exact_long: bool,
    /// Whether the command withholds the implicit `-V` short for version.
    pub no_implicit_version: bool,
    /// Valued long options that require an attached value.
    pub equals_only: S::List<char>,
    /// Short options that require an attached value.
    pub attached_values: S::List<char>,
    /// Short options that require a separate value.
    pub separated_values: S::List<char>,
    /// Short options accepting a leading numeric value.
    pub prefixed_values: S::List<char>,
    /// Option memberships in mutually exclusive groups.
    pub exclusive_groups: S::List<ExclusiveRule>,
    /// Generic key-value tags for downstream consumers.
    pub tags: S::List<(S::Text, S::Text)>,
    /// Body paragraphs between summary and Options.
    pub description: S::List<S::Text>,
    /// Content placed after auto-generated Options section.
    pub extra: S::List<S::Text>,
    /// Exit Status section content.
    pub exit_status: S::List<S::Text>,
}

impl CommandDef<Static> {
    /// A zero-valued base so a literal survives new fields being added
    pub const EMPTY: Self = Self {
        name: "",
        about: "",
        short_doc: "",
        style: Style::Posix,
        help_style: HelpStyle::Bash,
        on_unknown: OnUnknown::Reject,
        permute: false,
        flags: &[],
        positionals: &[],
        has_rest: false,
        rest_label: "",
        rest_hidden: false,
        rest_desc: "",
        rest_default: "",
        rest_required: false,
        value_rules: &[],
        numeric_operands: &[],
        first_numeric_value: None,
        exact_long: false,
        no_implicit_version: false,
        equals_only: &[],
        attached_values: &[],
        separated_values: &[],
        prefixed_values: &[],
        exclusive_groups: &[],
        tags: &[],
        description: &[],
        extra: &[],
        exit_status: &[],
    };
}

impl Default for CommandDef<Owned> {
    fn default() -> Self {
        Self {
            name: String::new(),
            about: String::new(),
            short_doc: String::new(),
            style: Style::Posix,
            help_style: HelpStyle::Bash,
            on_unknown: OnUnknown::Reject,
            permute: false,
            flags: Vec::new(),
            positionals: Vec::new(),
            has_rest: false,
            rest_label: String::new(),
            rest_hidden: false,
            rest_desc: String::new(),
            rest_default: String::new(),
            rest_required: false,
            value_rules: Vec::new(),
            numeric_operands: Vec::new(),
            first_numeric_value: None,
            exact_long: false,
            no_implicit_version: false,
            equals_only: Vec::new(),
            attached_values: Vec::new(),
            separated_values: Vec::new(),
            prefixed_values: Vec::new(),
            exclusive_groups: Vec::new(),
            tags: Vec::new(),
            description: Vec::new(),
            extra: Vec::new(),
            exit_status: Vec::new(),
        }
    }
}

/// Runtime-owned command metadata
pub type OwnedCommandDef = CommandDef<Owned>;

/// Metadata for a positional argument slot.
#[derive(Debug, Clone, PartialEq, Eq)]
#[expect(
    clippy::exhaustive_structs,
    reason = "static config generated by derive"
)]
pub struct PositionalDef<S: Storage = Static> {
    /// Field name (used in error messages).
    pub name: S::Text,
    /// Whether the user must provide this argument.
    pub required: bool,
    /// Human-readable description (from doc comment).
    pub desc: S::Text,
    /// Label shown in help; the field name when empty.
    pub label: S::Text,
    /// Value used when the argument is omitted; none when empty.
    pub default_value: S::Text,
    /// When true, omit from generated help.
    pub hidden: bool,
    /// Whether help shows the label as accepting more than one value.
    pub spread: bool,
}

impl<S: Storage> CommandDef<S> {
    /// Command name
    pub fn name(&self) -> &str {
        self.name.as_ref()
    }

    /// Declared flags
    pub fn flags(&self) -> &[FlagDef<S>] {
        self.flags.as_ref()
    }

    /// Generic metadata tags
    pub fn tags(&self) -> &[(S::Text, S::Text)] {
        self.tags.as_ref()
    }

    /// Scan one invocation against this command shape
    pub fn scan<'a>(&'a self, args: &'a [&'a str]) -> Result<crate::parse::Scan<'a>, Error> {
        let policy = crate::parse::Policy::from_definition(self);
        crate::parse::scan_with_policy(
            args,
            self.flags(),
            policy,
            self.on_unknown,
            self.style,
            self.permute,
        )
    }
}
